#!/bin/bash
USAGE=$(
      cat <<-END
      aws utils 



END
)

#### Import utils ###############################################
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/../utils/utils.sh
source $SCRIPT_DIR/source_aws



#### Global Config. #############################################
# set -x  # Output commands being run.
set -e # Exit on error.å
FUNAME=$(basename "$0")
YMD=$(date '+%Y%m%d')


### Input Params and Defaults ##################################
[ $# -eq 0 ] && print_usage ###  No input print doc
task=$1





######  ???   ########################################
if [[ "$task" = ec2_iam ]]; then
	awsfile=$2 && [ -z $2 ] && print_usage
	artifacts=$3 && [ -z $3 ] && print_usage


  ec2_get_iam()



##### ?????  ########################################
elif [[ "$task" = set ]]; then
	awsfile=$2 && [ -z $2 ] && print_usage
	claws=$3 && [ -z $3 ] && print_usage	
	cmd="openssl pkcs12 -out $awsfile -in $claws -export"






exit 0
##### Generate ssh key
elif [[ "$task" = sshkey ]]; then
  # https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
  key=$2 && [ -z $2 ] && print_usage













exit 0
else
	print_usage
fi


































