#!/bin/bash
USAGE=$(
      cat <<-END
     Perform cert/key management operations
     ## TODO: Make <key> and <clcert> optional

     cert get <cert.pfx> key <key> 				#### Get private key in <key> file from the the pfx certificate (ex: cert get cert.pfx key pkey.key)
     cert get <cert.pfx> clcert <clcert> 			#### Get client cert in <clcert> file from the the pfx certificate (ex: cert get cert.pfx clcert clcert.pem)

     cert set <cert.pfx> <clcert> [key] [cacert]                #### Convert pfx certificate from client certificate and private key(optional), cacert(optional) (ex: cert set cert.pfx clcert.pem pkey.key cacert.cer)

     cert gen [key]						#### Create new public cert, private key(default=~/.ssh/ida_rsa, id_rsa.pub) (ex: cert gen pkey.key)

END
)

#### Import utils ###############################################
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/utils/utils.sh

#### Global Config. #############################################
# set -x  # Output commands being run.
set -e # Exit on error.å

FUNAME=$(basename "$0")
YMD=$(date '+%Y%m%d')

### Input Params and Defaults ##################################
[ $# -eq 0 ] && print_usage ###  No input print doc
task=$1





######  ???   ########################################
if [[ "$task" = get ]]; then
	certfile=$2 && [ -z $2 ] && print_usage
	artifacts=$3 && [ -z $3 ] && print_usage

	case $artifacts in
		key)    key=$4 && [ -z $4 ] && print_usage
			openssl pkcs12 -in $certfile -nodes -nocerts -nokeys -out $key           ;;
		clcert) clcert=$4 && [ -z $4 ] && print_usage
			openssl pkcs12 -in $certfile -nodes -clcerts -out $clcert                ;;
		*)      echo "'$artifacts' not recognized"                                       ;;
	esac
	exit 0



##### ?????  ########################################
elif [[ "$task" = set ]]; then
	certfile=$2 && [ -z $2 ] && print_usage
	clcert=$3 && [ -z $3 ] && print_usage	
	cmd="openssl pkcs12 -out $certfile -in $clcert -export"

	for arg in "${@:4}"
	do
		if [[ -n $arg ]]; then
			base=${arg%.*} && ext=${arg#$base.}
			case $ext in
				key)    cmd+=" -inkey $arg"                                              ;;
				cer)	cmd+=" -certfile $arg"						 ;;
				crt)	cmd+=" -certfile $arg"						 ;;
			esac
		fi
	done
	eval "$cmd"





exit 0

##### Generate ssh key
elif [[ "$task" = sshkey ]]; then
  # https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
  key=$2 && [ -z $2 ] && print_usage
	#ssh-keygen -f $key
  INFO="ssh-keygen -t rsa -b 4096 -C "your_email@example.com" "


  echo $INFO
   




exit 0
else
	print_usage
fi
