#!/bin/bash

USAGE=$(
      cat <<-END
     Perform zip operations based on the compression mechanism

     zzip uncmp archive.tar target			         	#### Uncompress the file to target directory(default=PWD)  (ex: zzip uncmp archive.tar unarchive/)
     zzip cmp archive.tar source1, [source2...]	[maxfilesize=1G]	#### Compress and/or archive the source files with size maxfilesize=size(ex: 1K, 5G, 6M, default=1G). (ex: zzip cmp archive.tar file1 dir2)

END
)

#### Import utils ##################################
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/utils/utils.sh

#### Global Config. #################################
# set -x  # Output commands being run.
set -e # Exit on error.å

FUNAME=$(basename "$0")
YMD=$(date '+%Y%m%d')

### Input Params and Defaults ##################################
[ $# -eq 0 ] && print_usage ###  No input print doc
task=$1

### Core ###########################################
if [[ "$task" = uncmp ]]; then
	zipfile=$2 && [ -z $2 ] && echo -e $USAGE && zipfile="invalid"
	targetdir=$3 && [ -z $3 ] && targetdir=$(pwd)

	case $zipfile in
		*.zip)      unzip "$zipfile" -d $targetdir                           ;;
		*.tar)      tar -xvf "$zipfile"  -C $targetdir                       ;;
		*.tgz)      tar -zxvf "$zipfile" -C $targetdir                       ;;
		*.tar.xz)   tar -xvf "$zipfile"  -C $targetdir                       ;;
		*.tar.bz2)  tar -jxvf "$zipfile" -C $targetdir                       ;;
		*.tar.gz)   tar -zxvf "$zipfile" -C $targetdir                       ;;
		*.7z)       7z x "$zipfile" -o $targetdir                            ;;
		*.rar)      7z x "$zipfile" -o $targetdir                            ;;
		*)          echo "'$zipfile' Format not recognized"                  ;;
	esac
	exit 0
elif [[ "$task" = cmp ]]; then
	zipfile=$2 && [ -z $2 ] && print_usage
	limit="maxfilesize=[0-9]+[BKMG]"
	maxfilesize="1G"
	length=$(($#))
	last="${!#}"
	filestocmp=()

	if [[ $last =~ $limit ]]; then
		maxfilesize=${last#*=}
		sourcefiles=${@:3:$length-3}
	else
		sourcefiles=${@:3:$length-2}
	fi


	[ ${#sourcefiles[@]} -eq 0 ] && print_usage

	#### If a file is a directory, filter out files less than 1 GB to compress ####
	for file in $sourcefiles
	do
		[ -f $file ] && filestocmp+=($file)
		[ -d $file ] && filestocmp+=$(find $file -type f -size $maxfilesize | paste -sd " ")
	done

	echo "Files to compress:" ${filestocmp[@]}
	echo "Max file size:" $maxfilesize

	case $zipfile in
		*.zip)      zip "$zipfile" ${filestocmp[@]}                              ;;
		*.tar)      tar -cvf "$zipfile" "${filestocmp[@]}"		         ;;
		*.tgz)      tar -zcvf "$zipfile" ${filestocmp[@]}                        ;;
		*.tar.xz)   tar -Jcvf "$zipfile" ${filestocmp[@]}                        ;;
		*.tar.bz2)  tar -jcvf "$zipfile" ${filestocmp[@]}                        ;;
		*.tar.gz)   tar -zcvf "$zipfile" ${filestocmp[@]}                        ;;
		*.7z)       7z a "$zipfile" ${filestocmp[@]}                             ;;
		*.rar)      rar a "$zipfile" ${filestocmp[@]}                            ;;
		*)          echo "'$zipfile' Format not recognized"                      ;;
	esac
	exit 0
else
      echo $USAGE
fi
